version: '3.8'

services:
  alopecosa-crawler:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    container_name: alopecosa-fabrilis-crawler
    ports:
      - "5000:5000"
    environment:
      # Flask configuration
      - FLASK_ENV=production
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY:-alopecosa-fabrilis-spider-2024}
      
      # Performance optimizations
      - PYTHONOPTIMIZE=1
      - PYTHONHASHSEED=random
      - PYTHONUNBUFFERED=1
      
      # OpenAI API configuration (optional)
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-3.5-turbo}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-ada-002}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-400}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.2}
      
      # AI thresholds
      - AI_RELEVANCE_THRESHOLD=${AI_RELEVANCE_THRESHOLD:-0.6}
      - AI_QUALITY_THRESHOLD=${AI_QUALITY_THRESHOLD:-0.7}
      - AI_SIMILARITY_THRESHOLD=${AI_SIMILARITY_THRESHOLD:-0.9}
      
      # Rate limiting
      - OPENAI_RPM_LIMIT=${OPENAI_RPM_LIMIT:-60}
      - OPENAI_CONCURRENT_LIMIT=${OPENAI_CONCURRENT_LIMIT:-5}
      
      # Crawler settings
      - ALOPECOSA_USER_AGENT=${ALOPECOSA_USER_AGENT:-Alopecosa-Fabrilis-Crawler/1.0}
    
    volumes:
      # Use named volumes for better performance
      - crawler_data:/app/data
      - crawler_results:/app/crawl_results
      - crawler_logs:/app/logs
      
      # Mount templates for easy customization
      - ./templates:/app/templates:ro
    
    restart: unless-stopped
    
    # Optimized resource allocation
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1.0'
    
    # Performance optimizations
    shm_size: '256mb'
    tmpfs:
      - /tmp:size=100m
      - /var/tmp:size=100m
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Performance tuning
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
      nproc:
        soft: 4096
        hard: 4096

  # Optional: Add a simple nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    container_name: alopecosa-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - alopecosa-crawler
    restart: unless-stopped
    profiles:
      - production
    
    # Nginx performance optimizations
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

volumes:
  crawler_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
  crawler_results:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./crawl_results
  crawler_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs
