name = "alopecosa-crawler"
main = "src/cloudflare_worker.py"
compatibility_date = "2024-01-01"
compatibility_flags = ["python_workers"]

# Python Workers specific configuration
[build]
command = "pip install -r requirements.txt"

[env.production]
name = "alopecosa-crawler-prod"

[env.staging]
name = "alopecosa-crawler-staging"

[site]
bucket = "./templates"

[triggers]
crons = []

[env.production.vars]
ENVIRONMENT = "production"

[env.staging.vars]
ENVIRONMENT = "staging"
